/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MiaItaliaRouteImport } from './routes/mia-italia'
import { Route as CittaIdRouteImport } from './routes/citta.$id'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiaItaliaRoute = MiaItaliaRouteImport.update({
  id: '/mia-italia',
  path: '/mia-italia',
  getParentRoute: () => rootRouteImport,
} as any)
const CittaIdRoute = CittaIdRouteImport.update({
  id: '/citta/$id',
  path: '/citta/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/mia-italia': typeof MiaItaliaRoute
  '/citta/$id': typeof CittaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/mia-italia': typeof MiaItaliaRoute
  '/citta/$id': typeof CittaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/mia-italia': typeof MiaItaliaRoute
  '/citta/$id': typeof CittaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz' | '/mia-italia' | '/citta/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz' | '/mia-italia' | '/citta/$id'
  id: '__root__' | '/' | '/quiz' | '/mia-italia' | '/citta/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  QuizRoute: typeof QuizRoute
  IndexRoute: typeof IndexRoute
  MiaItaliaRoute: typeof MiaItaliaRoute
  CittaIdRoute: typeof CittaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mia-italia': {
      id: '/mia-italia'
      path: '/mia-italia'
      fullPath: '/mia-italia'
      preLoaderRoute: typeof MiaItaliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citta/$id': {
      id: '/citta/$id'
      path: '/citta/$id'
      fullPath: '/citta/$id'
      preLoaderRoute: typeof CittaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  QuizRoute: QuizRoute,
  IndexRoute: IndexRoute,
  MiaItaliaRoute: MiaItaliaRoute,
  CittaIdRoute: CittaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
